[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20
viaIR = true
solc = "0.8.20"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

remappings = []

[rpc_endpoints]
arbSepolia = "${ARB_SEPOLIA_RPC_URL}"

[etherscan]
arbSepoliaKey = { url = "https://api-sepolia.arbiscan.io/api", chain = 421614, key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
