/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICTM3525XMetadataDescriptor,
  ICTM3525XMetadataDescriptorInterface,
} from "../../../../contracts/periphery/interface/ICTM3525XMetadataDescriptor";

const _abi = [
  {
    inputs: [],
    name: "constructContractURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "slot",
        type: "uint256",
      },
    ],
    name: "constructSlotURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "constructTokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICTM3525XMetadataDescriptor__factory {
  static readonly abi = _abi;
  static createInterface(): ICTM3525XMetadataDescriptorInterface {
    return new utils.Interface(_abi) as ICTM3525XMetadataDescriptorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICTM3525XMetadataDescriptor {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ICTM3525XMetadataDescriptor;
  }
}
