/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interface from "./interface";
export { ERC3525MetadataDescriptor__factory } from "./ERC3525MetadataDescriptor__factory";
export { ERC3525MetadataDescriptorUpgradeable__factory } from "./ERC3525MetadataDescriptorUpgradeable__factory";
