/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICTM3525XMetadataDescriptor } from "./ICTM3525XMetadataDescriptor";
export type { ICTM3525XMetadataDescriptorUpgradeable } from "./ICTM3525XMetadataDescriptorUpgradeable";
