/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICTMRWA001MetadataDescriptorUpgradeable,
  ICTMRWA001MetadataDescriptorUpgradeableInterface,
} from "../../../../contracts/periphery/interface/ICTMRWA001MetadataDescriptorUpgradeable";

const _abi = [
  {
    inputs: [],
    name: "constructContractURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "slot",
        type: "uint256",
      },
    ],
    name: "constructSlotURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "constructTokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICTMRWA001MetadataDescriptorUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): ICTMRWA001MetadataDescriptorUpgradeableInterface {
    return new utils.Interface(
      _abi
    ) as ICTMRWA001MetadataDescriptorUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICTMRWA001MetadataDescriptorUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ICTMRWA001MetadataDescriptorUpgradeable;
  }
}
