/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  PayableOverrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  NonReceiverMockUpgradeableWithInit,
  NonReceiverMockUpgradeableWithInitInterface,
} from "../../../../contracts/mocks/CTMRWA001BaseMockUpgradeableWithInit.sol/NonReceiverMockUpgradeableWithInit";

const _abi = [
  {
    inputs: [],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
] as const;

const _bytecode =
  "0x60808060405260005460ff8160081c16159182809361016f575b8015610158575b156100ff575060ff198116600117600055816100ed575b506000549060ff8260081c16156100945761005b575b604051603a908161017d8239f35b61ff0019166000557f7f26b83ff96e1f2b6a682f133852f6798a09c465da95921460cefb3847402498602060405160018152a13861004d565b60405162461bcd60e51b815260206004820152602b60248201527f496e697469616c697a61626c653a20636f6e7472616374206973206e6f74206960448201526a6e697469616c697a696e6760a81b6064820152608490fd5b61ffff19166101011760005538610037565b62461bcd60e51b815260206004820152602e60248201527f496e697469616c697a61626c653a20636f6e747261637420697320616c72656160448201526d191e481a5b9a5d1a585b1a5e995960921b6064820152608490fd5b50303b1580156100205750600160ff831614610020565b50600160ff83161061001956fe600080fdfea2646970667358221220b2748377c0b5613566331490e318ccd8e9cfc176010c1e976378ec34014ba38a64736f6c63430008140033";

type NonReceiverMockUpgradeableWithInitConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NonReceiverMockUpgradeableWithInitConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NonReceiverMockUpgradeableWithInit__factory extends ContractFactory {
  constructor(...args: NonReceiverMockUpgradeableWithInitConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<NonReceiverMockUpgradeableWithInit> {
    return super.deploy(
      overrides || {}
    ) as Promise<NonReceiverMockUpgradeableWithInit>;
  }
  override getDeployTransaction(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): NonReceiverMockUpgradeableWithInit {
    return super.attach(address) as NonReceiverMockUpgradeableWithInit;
  }
  override connect(
    signer: Signer
  ): NonReceiverMockUpgradeableWithInit__factory {
    return super.connect(signer) as NonReceiverMockUpgradeableWithInit__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NonReceiverMockUpgradeableWithInitInterface {
    return new utils.Interface(
      _abi
    ) as NonReceiverMockUpgradeableWithInitInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NonReceiverMockUpgradeableWithInit {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as NonReceiverMockUpgradeableWithInit;
  }
}
