/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interface from "./interface";
export type { interface };
export type { CTM3525XMetadataDescriptor } from "./CTM3525XMetadataDescriptor";
export type { CTM3525XMetadataDescriptorUpgradeable } from "./CTM3525XMetadataDescriptorUpgradeable";
