/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC3525Metadata } from "./IERC3525Metadata";
export type { IERC3525MetadataUpgradeable } from "./IERC3525MetadataUpgradeable";
export type { IERC3525SlotApprovable } from "./IERC3525SlotApprovable";
export type { IERC3525SlotApprovableUpgradeable } from "./IERC3525SlotApprovableUpgradeable";
export type { IERC3525SlotEnumerable } from "./IERC3525SlotEnumerable";
export type { IERC3525SlotEnumerableUpgradeable } from "./IERC3525SlotEnumerableUpgradeable";
export type { IERC3525SlotManageable } from "./IERC3525SlotManageable";
export type { IERC3525SlotManageableUpgradeable } from "./IERC3525SlotManageableUpgradeable";
export type { IERC721Enumerable } from "./IERC721Enumerable";
export type { IERC721EnumerableUpgradeable } from "./IERC721EnumerableUpgradeable";
export type { IERC721Metadata } from "./IERC721Metadata";
export type { IERC721MetadataUpgradeable } from "./IERC721MetadataUpgradeable";
