/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  NonReceiverMockUpgradeable,
  NonReceiverMockUpgradeableInterface,
} from "../../../contracts/mocks/NonReceiverMockUpgradeable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
] as const;

const _bytecode =
  "0x60808060405234601357603a908160198239f35b600080fdfe600080fdfea2646970667358221220a22363492b3a925cc9d348cbfffe14befc8c055913a27544e161b68bd0b5836564736f6c63430008140033";

type NonReceiverMockUpgradeableConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NonReceiverMockUpgradeableConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NonReceiverMockUpgradeable__factory extends ContractFactory {
  constructor(...args: NonReceiverMockUpgradeableConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<NonReceiverMockUpgradeable> {
    return super.deploy(overrides || {}) as Promise<NonReceiverMockUpgradeable>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): NonReceiverMockUpgradeable {
    return super.attach(address) as NonReceiverMockUpgradeable;
  }
  override connect(signer: Signer): NonReceiverMockUpgradeable__factory {
    return super.connect(signer) as NonReceiverMockUpgradeable__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NonReceiverMockUpgradeableInterface {
    return new utils.Interface(_abi) as NonReceiverMockUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NonReceiverMockUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as NonReceiverMockUpgradeable;
  }
}
